### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by cobcorn** [pjanouch/uirc3#3]
I've tried screwing around with some things suggested here: https://stackoverflow.com/questions/1620918/cmake-and-libpthread but I know very little about C and even less about CMake.

Here is a log of my terminal:

```
~/uirc3-0.9.5/build > cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DWANT_READLINE=ON -DWANT_LIBEDIT=OFF -DWANT_LUA=ON
CMake Error at CMakeLists.txt:49 (include):
  include could not find load file:

    AddThreads


-- Checking for one of the modules 'lua53;lua5.3;lua-5.3;lua>=5.3'
-- Checking for module 'ncursesw'
--   Found ncursesw, version 6.0.20150808
CMake Error at CMakeLists.txt:162 (add_threads):
  Unknown CMake command "add_threads".
```
I'm using Void Linux and have installed all dependencies.

**Comment by pjanouch** [comment]
Recursive checkout.

    $ git submodule init
    $ git submodule update
